name: Build and release

on:
  push: {}

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up Node environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install NPM dependencies
        working-directory: ./fixtures/npm
        shell: bash
        run: npm install
      - name: Release
        working-directory: ./fixtures/npm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  inspect-env:
    runs-on: ubuntu-latest
    steps:
      - name: Read env vars
        run: env
      - name: Read GitHub event
        run: cat $GITHUB_EVENT_PATH

  inspect-gh-context:
    runs-on: ubuntu-latest
    steps:
      - name: Print context
        shell: bash
        run: echo ${{ toJSON(github) }}
