name: Create SBOM document and upload as release asset

on:
  release:
    types:
      - published

jobs:
  publish-sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4

      - name: Generate CycloneDX SBOM document
        uses: ./.github/actions/sbom-generator-cyclonedx-golang
        with:
          repo_token: ${{ secrets.BOT_TOKEN }}
