name: Release and publish SBOM asset

on:
  release:
    types:
      - published

jobs:
  publish-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Generate CycloneDX SBOM document
        uses: ./.github/actions/sbom-generator-cyclonedx

  inspect-env:
    runs-on: ubuntu-latest
    steps:
      - name: Read env vars
        run: env
      - name: Read GitHub event
        run: cat $GITHUB_EVENT_PATH
