name: Release and publish SBOM asset

on:
  release:
    types:
      - published

jobs:
  publish-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Generate CycloneDX SBOM document
        uses: ./.github/actions/sbom-generator-cyclonedx

  inspect-release-assets-url:
    runs-on: ubuntu-latest
    steps:
      - name: Print release assets URL
        shell: bash
        run: echo ${{ github.event.release.assets_url }}
