name: Create SBOM document and upload as release asset

on:
  release:
    types:
      - published

jobs:
  publish-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up Node environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install NPM dependencies
        working-directory: ./fixtures/npm
        shell: bash
        run: npm install
      - name: Generate CycloneDX SBOM document
        uses: ./.github/actions/sbom-generator-cyclonedx-npm
        with:
          repo_token: ${{ secrets.BOT_TOKEN }}
