name: Create and publish release

on:
  push: {}

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Set up Node environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Release
        working-directory: ./fixtures/npm
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: npx semantic-release
