name: Release and publish SBOM asset

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up Node environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Release
        working-directory: ./fixtures/npm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --branches=main
      - name: Generate CycloneDX SBOM document
        uses: ./.github/actions/sbom-generator-cyclonedx

  inspect-env:
    runs-on: ubuntu-latest
    steps:
      - name: Read env vars
        run: env
      - name: Read GitHub event
        run: cat $GITHUB_EVENT_PATH
