name: NPM CycloneDX JSON generator

on:
  push: {}
  release:
    types:
      - published

jobs:
  npm-cdx-generation:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Generate CycloneDX SBOM document
        uses: ./.github/actions/sbom-generator-cyclonedx

  inspect-env:
    runs-on: ubuntu-latest
    steps:
      - name: Read env vars
        run: env
      - name: Read GitHub event
        run: cat $GITHUB_EVENT_PATH
