name: NPM CycloneDX JSON generator

on:
  push: {}
  release:
    types:
      - created
      - published

jobs:
  npm-cdx-generation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm i -g @cyclonedx/cyclonedx-npm

      - name: Install NPM dependencies
        working-directory: ./fixtures/npm
        run: npm i

      - name: Generate CycloneDX document
        working-directory: ./fixtures/npm
        run: npx cyclonedx-npm > sbom.cdx.json

      - name: Store produced SBOM
        uses: actions/upload-artifact@v3
        with:
          name: sbom.cdx.json
          path: ./fixtures/npm/sbom.cdx.json

  inspect-env:
    runs-on: ubuntu-latest
    steps:
      - name: Read env vars
        run: env
      - name: Read GitHub event
        run: cat $GITHUB_EVENT_PATH
